import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'bayam-organik',
    name: 'Bayam Hijau Organik',
    description: 'Bayam hijau organik pilihan yang ditanam tanpa pestisida kimia di dataran tinggi Sigi. Memiliki tekstur daun yang lembut dan rasa yang segar. Kaya akan zat besi, vitamin A, dan vitamin C. Sangat cocok untuk olahan sayur bening, smoothie sehat, atau tumisan keluarga.',
    price: 8500,
    originalPrice: 10000,
    discountPercentage: 15,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBl6tOXZ698LpEyAsMagvK2CzWomyUO9TMD0T9F4Oii5DiKqr_wYlJPcGqPAzndm3juj3WhZBUjgAiAepNFNCWuqA5czQnoscp-2RveuGUNCRVZpsLjlzUuLCo4OZXjpxX-LKI-KA7p1KsRo-5n7mGdBRTcSprUeYTzJyr7Sgw-ihOgOsIzgo_zHrAp8QiRwMfbRHPFjcztQyPIC1KdXVADvBISEc0YvpRRgvQ12bPS1V9JNsS6UnzJviiy6itNZeDxURWXCvPulCTh',
    category: 'sayur',
    unit: 'ikat',
    origin: 'Kebun Sigi',
    isBestSeller: false,
    isPromo: true,
    availableQty: 24,
    unitAvailableText: '24 pcs',
    features: ['Organik', 'Panen Hari Ini', 'Vacuum Pack']
  },
  {
    id: 'bayam-hijau-segar',
    name: 'Bayam Hijau Segar',
    description: 'Bayam hijau segar diikat rapi langsung dari petani tradisional. Sangat cocok dimasak kuah bening hangat yang menyegarkan tubuh.',
    price: 4500,
    rating: 4.7,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_rNvIPopsj8KF3yqMvf-2NFIZAzr-SS72Ti_fmULitbNFznla3BNZ0W9QfJCBBa1gvjwgvV5flKc6ZXoj_zaKW4czYZbz0Rymsb3VSuOn-e9IsRZeHavcI0kP43NgIoakfee20o7FtzsSy6jXC5oaA9ermyC6AoCsyHjZ-fI3aWCzLoK-IxszTWvbB9IXya6lo1q8kKO6WGzFTgmNhfC_UMMY2kXerISD4lcKjuGozy3ONvIUR-rZzHO1-c98-eAJb-wAlnOa3Qoz',
    category: 'sayur',
    unit: 'ikat (~250g)',
    origin: 'Kebun Sigi',
    isBestSeller: false,
    isPromo: true,
    availableQty: 24,
    unitAvailableText: '24 pcs'
  },
  {
    id: 'wortel-organik',
    name: 'Wortel Organik',
    description: 'Wortel pilihan dari Berastagi ditanam secara natural dan organik, kaya akan Beta-Karoten dan rasa manis alami. Dikemas higienis siap masak.',
    price: 12500,
    rating: 4.9,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAP9PULXMyKn2zyIBcF9gs_kmWamRk4FgbJwU52ZTlvyep-GTBMbl8IoSHiOvgXDOqd0UGad5KoFPLb2YnRe6Eb6x8a1NQSlVowRIrq3QFlTJFOHcObQp6-KM2DhSw1fxgnJ3CoSiJEmcnJ_9hsr0Bw4_s6523QpNeAznUn_fLL3P4BNSsKIp76W_S1mDEaaFeS4WGKbs5mOP4BZmXX3znA9_8HwP-6n7WSLC-O5wC9OVBeqL3rcfFICd-Wjy5PFkrmGZOHcPY9nrtY',
    category: 'sayur',
    unit: '500gr',
    origin: 'Kaki Gunung Sinabung',
    isBestSeller: true,
    isPromo: false,
    availableQty: 15,
    unitAvailableText: '15 kg',
    features: ['Organik', 'Fresh Harvest', 'Tanpa Pestisida']
  },
  {
    id: 'wortel-berastagi-super',
    name: 'Wortel Berastagi Super',
    description: 'Wortel Berastagi kualitas ekspor berukuran seragam. Manis renyah dan memiliki warna orange yang sangat pekat pertanda kandungan vitamin melimpah.',
    price: 12000,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7a6_VR4_XqbhqAodwaITRZYo4_qSGQNEdhrtKL1zvwnl004L_RzPYvQeKbP_Hz14tPRSvi8roks5Vt0kFrrPO-ezxK_FJ3ulqSZm5r50XygX-j30X7GySl7a_-Xj8duhUYhK6JRTGoynEk2aY4XtHpsas2p_KRLTeUI8yvOKtv3YvDYA-cxwjASiXzCtm0SjFgzoJEslzrDV8GYtZxE4jG05921O5UAVpHW2bQ3BzRDljjPOqWyhKrJFnsjz9H7niJJ0lP-lxB8ID',
    category: 'sayur',
    unit: '500 gram',
    origin: 'Berastagi Highland',
    isBestSeller: false,
    isPromo: false,
    availableQty: 15,
    unitAvailableText: '15 kg'
  },
  {
    id: 'tomat-cherry',
    name: 'Tomat Cherry Red',
    description: 'Tomat cherry manis, berkilau merah prima, kaya antioksidan Likopen, dipetik saat ranum sempurna. Cocok sebagai kudapan segar langsung atau sebagai pelengkap salad premium.',
    price: 18000,
    rating: 4.9,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCAS0AUW8HPiPPCqifPTO-pI45iAyvt6LYJi3Vtlf8Gew0CjPa8v81CV0kqUcxff1DeDlAELs1KwKAluusRfBxsbdjX-cnXOfjYbb7IQXeUNa_5hvJhug0zOMKBJq0ZvJWlQvQ5bTmIFwFpPe8kc4X2i1R8SMEzh2Qms2JlVKnKCPYlwHT_nWLDgKbyMrMkoL5rCRV7QGEEuydYgSLpNOf1Mw1YNdZ2u7wfC3O5uJP0ZaMDU2Qp9l4Rak1B0DD8ob997uoz1dqCrBx1',
    category: 'sayur',
    unit: '250gr',
    origin: 'Cianjur Lestari',
    isBestSeller: true,
    isPromo: false,
    availableQty: 8,
    unitAvailableText: '8 pcs',
    features: ['Hidroponik', 'Super Sweet', 'Hygienic Pack']
  },
  {
    id: 'tomat-cherry-organik',
    name: 'Tomat Cherry Organik',
    description: 'Tomat cherry berukuran mini rasa manis istimewa ditanam secara organik murni berkualitas prima.',
    price: 18500,
    rating: 4.7,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRPQQ894zfal8dyVVhMqVRZBF691nIMfkySh6-XxPvc_p1VFsTrZu0f-ZVi5B0mp8_mLLJrxTZvBQbhw5NbRYXEK3hwMkUzEqYdFSenBrJAP38QVBwx6Jlk-iXHIK_kr28JXpqFHMJwLUlpPeYlWRm-2dGnwRxu3oXgSGh5kPVOopOO-FfjOCDQG4vOoncthq8h8KcmXWfCa0FE2Oee3Gi0GNTWONKJsPSerJNyB1VHNtwK4xBcsmymIYKFzIF-NAhJC03d9bcm4k-',
    category: 'sayur',
    unit: '250 gram',
    origin: 'Cianjur Lestari',
    isBestSeller: false,
    isPromo: false,
    availableQty: 6,
    unitAvailableText: 'Stok Terbatas'
  },
  {
    id: 'alpukat-mentega-super',
    name: 'Alpukat Mentega Super',
    description: 'Alpukat dengan daging super tebal, lembuuuut bagai mentega dengan warna kuning keemasan yang manis gurih khas. Dijamin matang sempurna.',
    price: 35000,
    rating: 4.9,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgSbHt8qOTrPUnAQuX2v_jtsQ4l0v7uDXJO5MF2Aa4JOI2NmR22XTOWb6fUDt6pi4rd72K1KKeLcgn9c5DK0hUGykix4sPjs214Hcrv3GQVtEbIeBx5-q9OfIGXf9sN_N11L06Kws-1f9p25CSZNPnwxarwPjYc6rZ0WN1xbfgo1kVogIGZuki7FE0vavE1k2wfuGun_Bcyl3eXD15N7lBpyjITGgKLto9t6V16UnkBJimUuN8l-90IhLZdCiA6067N_8WtTNJrOkW',
    category: 'buah',
    unit: '1kg',
    origin: 'Kebun Garut',
    isBestSeller: true,
    isPromo: false,
    availableQty: 40,
    unitAvailableText: 'Tersedia 40 kg',
    features: ['Grade A', 'Garansi Matang', 'Daging Tebal']
  },
  {
    id: 'alpukat-mentega-sigi',
    name: 'Alpukat Mentega Sigi',
    description: 'Alpukat Mentega Sigi legit berlemak tinggi siap saji untuk jus kesehatan, MPASI buah hati, atau hidangan segar es kelapa alpukat.',
    price: 35000,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDglVcjQbinAbHYzLl1eClTx9HgUJzC_mNwD-MJYNqoGFSlsCkjj0f7EwoFXDWNj4X7GpzYcdPquUBLAmO3O1PDkkpgLp1kEQhg9-XEYNtvc-9IhdGbPzBYEN2Jcz6k76gPhotn_1o6ejTh3HkyZEo6Ct3slWJ3dIYj9N9yzR0EMlB_Gww3HX6cIhzqF-BzG3RB1UyylBj3B8k_JungCm-CcZndqQhLbkzSMZYzG9magl9-ytfT3Yitrh7Z8GFrqLU918dH65kK-eHs',
    category: 'buah',
    unit: 'kg (isi 3-4)',
    origin: 'Kebun Garut',
    isBestSeller: false,
    isPromo: false,
    availableQty: 30,
    unitAvailableText: 'Tersedia 30 kg'
  },
  {
    id: 'pisang-cavendish',
    name: 'Pisang Cavendish Sunpride',
    description: 'Pisang Cavendish matang alami, kulit kuning mulus mengilap bebas bercak, daging buah lembut padat manis merata segar berstamina tinggi harian.',
    price: 22000,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4I9xIcE3pXLf2-y9OxX-ZGyo_m-RDAR4pMQ_qHSUSkdfCa9E2OTsCEDyJFp2DkFPPnr5kCBxMxaQRjplwMLoSIfxHsJS3SQnvsPKdsmW1Udk952-4aMmdqavmDSV5gPdJqLnJAqvMxCo5IcGHyKizJqSkioTMP6oTarLBO7RiiDPmjRfb1f8KbvfcctC_iWfXQPaef04zlcVymkK8U4Q5LSBO9cNe577oVURpefZFGaLd-Oa3tiqk3xDxPBZFEg-dzNmGn2ywsffk',
    category: 'buah',
    unit: 'sisir',
    origin: 'Lampung Timur',
    isBestSeller: false,
    isPromo: false,
    availableQty: 50,
    unitAvailableText: 'Stok Melimpah'
  },
  {
    id: 'bawang-merah-brebes',
    name: 'Bawang Merah Brebes',
    description: 'Bawang merah Brebes super wangi dan beraroma gurih tajam, kadar air rendah kering sempurna tahan disimpan lama.',
    price: 15000,
    rating: 4.7,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDs4PHMgG313vKTutvpwvraE0vE36g8vKIRlqgYFLJJ7-W1Ydd5CDu4OEwNJh7BLCAvb81G_yErZTEo_wFUsgmrs316aVRIPDOtLAaDgiueECWKXCGAJE-K7PhtCKiGEPYpsaBAigtiQFAWTCw3Ibh2AEuJNLfQdz-SeG-JPWeKkUN_owILEiqolwxn8CrNlKwc6WvLnTi5MKyJWBii_JPsMNTNupmCmsOYLMQ_Jx7O3qvhICjOHaWOteYEbklKvadBf8DeiQdBG3l-',
    category: 'sembako',
    unit: '250 gram',
    origin: 'Lahan Brebes',
    isBestSeller: false,
    isPromo: false,
    availableQty: 10,
    unitAvailableText: 'Tersedia 10 kg'
  },
  {
    id: 'paprika-merah',
    name: 'Paprika Merah Import',
    description: 'Paprika merah segar tebal rasa manis juicy alami renyah tanpa pestisida berbahaya.',
    price: 14500,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCH0_M6Ql7sppi9uFZYkLKNdCmb7Bqy84fgEsvdEErSvM14w63jw3vMN616XDgBVktJ_lxv07mhA-rSzohJZZShI7MpaoAPx6C1HvrTx2aJLAk-3QcKCPOCRrgXJKbDp8Q4M0brO06dpb0WF_DJCnbw70YYyCfTUcMnN_gl_-BAMUVyP5Z0ocLZGYORFi7ckco-fxPUQNbRxOhWlA30kkDhWzWuAG1nAZ-EyEiH-yEZG4a0xC_1A39LcEee4J_INf-nLXxOCrHo7xCz',
    category: 'sayur',
    unit: 'buah',
    origin: 'Kebun Lembang',
    isBestSeller: false,
    isPromo: false,
    availableQty: 8,
    unitAvailableText: 'Tersedia 8 pcs'
  },
  {
    id: 'jeruk-sunkist-navel',
    name: 'Jeruk Sunkist Navel',
    description: 'Jeruk Sunkist harum dengan bulir berair melimpah, rasa manis segar kaya vitamin C penambah imunitas kesehatan.',
    price: 48000,
    rating: 4.9,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBI4RoWAT-IL_oMNgJjivMLUyuJaGYn4Nf21fZM5obD9SKQXPS8lXwnpKzagA37bdh76sy47QMsOqUHQi5-H7ynY06keLoyF1jIFjgAl2YTBQyBJ3z2MdqSBvQygDX-iS_j6--UGdi8bNABv5oa62m_d-sj7qug4kbeQGd5xsVkwE1vvK2ZrXlTYlAzaVcRlOMmYkOyuv3ic56pesHwvqi2ZWN1_3YRz5wEcG3cufnrl3M_vstieqlJv93OGLkwF1gM9VsBr9BJM_Ex',
    category: 'buah',
    unit: 'kg (isi 5-6)',
    origin: 'Navel Orchard USA',
    isBestSeller: false,
    isPromo: false,
    availableQty: 25,
    unitAvailableText: 'Tersedia 25 kg'
  },
  {
    id: 'telur-ayam-kampung',
    name: 'Telur Ayam Kampung',
    description: 'Telur Ayam Kampung segar pilihan tinggi nutrisi dan protein murni. Bersih higienis siap konsumsi.',
    price: 28900,
    rating: 4.9,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQdnLN81y2hLXoe9Xs6kPHAs7vO9psdgPh2_Q48K5UyQY6xAUZASorkQ38G6OkQ4RATtsTdaiciJyEyb1f1EMgc1M6yHgDOf1iDUpu9HuvQ8C_P7HXzu-7L5-m3xGiUU8AfrfgWk9_mQ_4hgPQpvlr1qGkgiPlH9Lml2MA9HgwoSZTvGIRidHMw0cFFVJmtAYmLgQSWAb5VoHYRIl46rsAvi2gpZqnqOfsp7Z_wap99ahTSKO1pj7qn0LlwR4uDwHpey5ywiILJtKG',
    category: 'sembako',
    unit: '10 butir',
    origin: 'Peternakan Ayam Organik Sigi',
    isBestSeller: true,
    isPromo: false,
    availableQty: 12,
    unitAvailableText: 'Tersedia 12 pack'
  },
  {
    id: 'pakcoy-segar',
    name: 'Pakcoy Segar',
    description: 'Sayur pakcoy atau pokchoy renyah segar bebas pestisida dipanen langsung saat pesanan dipacking.',
    price: 6500,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-45ujv6eFUn6EMdPxMNMNuTkEmvKGNIq3VuHcsMDZy5G8cLpSVy0Y-drd6JaFtPUvZ6OH5XgWWyH9LgrEZ2TJDvUFe9qGAdNB4uedmFupqzJAjtMRtNkmj7uQ2GdMRRL9b7y62o9yRdIML1z4AfNPcd06FAh2QBw78QMw9ASaM6bWP5oHQd25CzAPfrX3fZMJ1pWJBWskRSa5oNmiCEuinCi9hRhWi3GeTTMY5TU1yjIPGgUa7X77a2sR6CSWeydMn139HY62OyX4',
    category: 'sayur',
    unit: '250g',
    origin: 'Kebun Vertikal Sigi',
    isBestSeller: false,
    isPromo: false,
    availableQty: 20,
    unitAvailableText: 'Tersedia 20 pcs'
  },
  {
    id: 'terong-ungu',
    name: 'Terong Ungu Premium',
    description: 'Terong ungu mengilap, mulus padat, dan tidak berulat. Nikmat sebagai masakan balado pedas gurih harian bumbu ulek rempah.',
    price: 9000,
    rating: 4.8,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDkIK-eqghqVEBLQtTOeY2f7CoBGiYDbCt6hUw3l-ON_kNYA9adu4fIt9_tjva0_Mdqax6TSy859_MuB8agwYLjuT-_ODiV9MoYauUYMfqR12Qg8cFmoJcPRLVzbCOM3ekwM1aU6x_yISpx6dRUJFNs6SZil3DUqSMyidRwINDt99c5ZKLuSxKGQa1b0PflzUipgVHtUgFepEOWPXtdzA2li2t4M74EeJ9c5A7eTfYzV-yxqRlp9-psgr_e4AVf2u_3iSVrahzR_i1b',
    category: 'sayur',
    unit: '500g',
    origin: 'Kebun Sayur Pluit',
    isBestSeller: false,
    isPromo: false,
    availableQty: 15,
    unitAvailableText: 'Tersedia 15 pcs'
  },
  {
    id: 'daging-sapi',
    name: 'Daging Sapi Gandik Segar',
    description: 'Daging sapi segar bagian gandik halal 100% dipotong pagi hari langsung dari jagal lokal, higienis tanpa air tambahan.',
    price: 68000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
    category: 'daging',
    unit: '500 gram',
    origin: 'RPH Sigi Lestari',
    isBestSeller: false,
    isPromo: false,
    availableQty: 10,
    unitAvailableText: 'Tersedia 10 kg',
    features: ['100% Halal', 'Sapi Lokal', 'Segar Tanpa Beku']
  }
];

export const INITIAL_ADDRESSES = [
  {
    label: 'Rumah (Utama)',
    fullAddress: 'Jl. Kebon Jeruk No. 12, Jakarta Barat, 11530'
  },
  {
    label: 'Apartemen Green Bay',
    fullAddress: 'Apartemen Green Bay, Pluit, Tower B, No 12, Jakarta Utara'
  },
  {
    label: 'Kantor Kerja',
    fullAddress: 'Gedung AIA Central Lt. 14, Sudirman Kav. 48, Jakarta Selatan'
  }
];
